In [2]:
import numpy as np 
   # Sales data: rows = products, columns = days 
sales_data = np.array([    [150, 200, 250, 300, 400, 350, 500],    [120, 180, 210, 240, 310, 280, 400],    [100, 130, 190, 220, 300, 270, 350],   [80,  90,  150, 180, 240, 220, 300],     [50,  60,  80,  100, 130, 120, 180]   ])

In [5]:
print("Shape of data is ",sales_data.shape)

Shape of data is  (5, 7)


In [7]:
print("Dimension of data is ",sales_data.ndim)

Dimension of data is  2


In [11]:
print("Data type of data is ",sales_data.dtype)

Data type of data is  int32


In [12]:
print("Data type of data is ",sales_data.size)

Data type of data is  35


In [14]:
print("Data type of data is ",sales_data.size*sales_data.itemsize)

Data type of data is  140


In [28]:
print("sales data for: Product 3 on Day 4 ",sales_data[2,3])
print("sales data for: Product 1 ",sales_data[0])
print("Sales data for last 2 days is ",sales_data[:,-2:])
print("Sales data for last 2 days is ",sales_data[:3])
print("Transpose of array: ",sales_data.T)


sales data for: Product 3 on Day 4  220
sales data for: Product 1  [150 200 250 300 400 350 500]
Sales data for last 2 days is  [[350 500]
 [280 400]
 [270 350]
 [220 300]
 [120 180]]
Sales data for last 2 days is  [[150 200 250 300 400 350 500]
 [120 180 210 240 310 280 400]
 [100 130 190 220 300 270 350]]
Transpose of array:  [[150 120 100  80  50]
 [200 180 130  90  60]
 [250 210 190 150  80]
 [300 240 220 180 100]
 [400 310 300 240 130]
 [350 280 270 220 120]
 [500 400 350 300 180]]
